export const AUTHENTICATION_APPLICATION_SERVICE = Symbol('AUTHENTICATION_APPLICATION_SERVICE');
export const IDENTITY_MANAGEMENT_APPLICATION_SERVICE = Symbol(
  'IDENTITY_MANAGEMENT_APPLICATION_SERVICE',
);
export const REGISTRATION_APPLICATION_SERVICE = Symbol('REGISTRATION_APPLICATION_SERVICE');
export const VERIFICATION_APPLICATION_SERVICE = Symbol('VERIFICATION_APPLICATION_SERVICE');
export const PASSWORD_RESET_APPLICATION_SERVICE = Symbol('PASSWORD_RESET_APPLICATION_SERVICE');
export const MFA_ENROLLMENT_APPLICATION_SERVICE = Symbol('MFA_ENROLLMENT_APPLICATION_SERVICE');
export const SESSION_MANAGEMENT_APPLICATION_SERVICE = Symbol(
  'SESSION_MANAGEMENT_APPLICATION_SERVICE',
);
export const TRUSTED_DEVICE_MANAGEMENT_APPLICATION_SERVICE = Symbol(
  'TRUSTED_DEVICE_MANAGEMENT_APPLICATION_SERVICE',
);
export const IDENTITY_LIFECYCLE_APPLICATION_SERVICE = Symbol(
  'IDENTITY_LIFECYCLE_APPLICATION_SERVICE',
);
export const IDENTITY_STATE_CHANGE_AUTHORIZATION = Symbol('IDENTITY_STATE_CHANGE_AUTHORIZATION');
export const MFA_REPLACEMENT_APPLICATION_SERVICE = Symbol('MFA_REPLACEMENT_APPLICATION_SERVICE');
export const RECOVERY_CODE_SET_APPLICATION_SERVICE = Symbol(
  'RECOVERY_CODE_SET_APPLICATION_SERVICE',
);
export const RECOVERY_REQUEST_APPLICATION_SERVICE = Symbol('RECOVERY_REQUEST_APPLICATION_SERVICE');
export const CSRF_PROTECTION = Symbol('CSRF_PROTECTION');
export const RATE_LIMITER = Symbol('RATE_LIMITER');
export const BASIC_AUDIT_LOGGER = Symbol('BASIC_AUDIT_LOGGER');
