export const AUTHENTICATION_APPLICATION_SERVICE = Symbol('AUTHENTICATION_APPLICATION_SERVICE');
export const IDENTITY_MANAGEMENT_APPLICATION_SERVICE = Symbol('IDENTITY_MANAGEMENT_APPLICATION_SERVICE');
export const REGISTRATION_APPLICATION_SERVICE = Symbol('REGISTRATION_APPLICATION_SERVICE');
export const VERIFICATION_APPLICATION_SERVICE = Symbol('VERIFICATION_APPLICATION_SERVICE');
export const CSRF_PROTECTION = Symbol('CSRF_PROTECTION');
export const RATE_LIMITER = Symbol('RATE_LIMITER');
export const BASIC_AUDIT_LOGGER = Symbol('BASIC_AUDIT_LOGGER');

