export const AUTHORIZATION_APPLICATION_SERVICE = Symbol('AUTHORIZATION_APPLICATION_SERVICE');
export const IDENTITY_ROLE_ASSIGNMENT_REPOSITORY = Symbol('IDENTITY_ROLE_ASSIGNMENT_REPOSITORY');
export const AUTHORIZATION_DECISION_REPOSITORY = Symbol('AUTHORIZATION_DECISION_REPOSITORY');
export const AUTHORIZATION_MUTATION = Symbol('AUTHORIZATION_MUTATION');
export const PRIVILEGED_ELIGIBILITY = Symbol('PRIVILEGED_ELIGIBILITY');
export const TRUSTED_WORKLOAD_KEY_RESOLVER = Symbol('TRUSTED_WORKLOAD_KEY_RESOLVER');
export const TRUSTED_WORKLOAD_REPLAY = Symbol('TRUSTED_WORKLOAD_REPLAY');
export const TRUSTED_PEER_CERTIFICATE = Symbol('TRUSTED_PEER_CERTIFICATE');
export const TRUSTED_WORKLOAD_VERIFIER = Symbol('TRUSTED_WORKLOAD_VERIFIER');
export const SELLER_OWNERSHIP_RESOLVER = Symbol('SELLER_OWNERSHIP_RESOLVER');
/** WEMP-M06-AUTHZ-001 §4 (D-07, sign-off 2026-08-17): fourth resolver scope. */
export const CUSTOMER_OWNERSHIP_RESOLVER = Symbol('CUSTOMER_OWNERSHIP_RESOLVER');
