export const AUTHORIZATION_APPLICATION_SERVICE = Symbol('AUTHORIZATION_APPLICATION_SERVICE');
export const IDENTITY_ROLE_ASSIGNMENT_REPOSITORY = Symbol('IDENTITY_ROLE_ASSIGNMENT_REPOSITORY');
export const AUTHORIZATION_DECISION_REPOSITORY = Symbol('AUTHORIZATION_DECISION_REPOSITORY');
export const AUTHORIZATION_MUTATION = Symbol('AUTHORIZATION_MUTATION');
