export const AUTHENTICATION_SECURITY_CLASSIFICATIONS = [
  'STANDARD_AUTHENTICATION',
  'PRIVILEGED_ADMIN_AUTHENTICATION',
  'SUPER_ADMIN_AUTHENTICATION',
] as const;
export type AuthenticationSecurityClassification =
  (typeof AUTHENTICATION_SECURITY_CLASSIFICATIONS)[number];
