export const VERIFICATION_PURPOSES = [
  'REGISTRATION_VERIFICATION',
  'PRIVILEGED_INVITATION_VERIFICATION',
  'CONTACT_CHANGE_VERIFICATION',
  'PASSWORD_RECOVERY',
  'ACCOUNT_RECOVERY',
  'MFA_ENROLLMENT',
  'MFA_AUTHENTICATION',
  'STEP_UP_AUTHENTICATION',
  'ADDITIONAL_SECURITY_VERIFICATION',
] as const;
export type VerificationPurpose = (typeof VERIFICATION_PURPOSES)[number];
