export const RECOVERY_OPERATION_CLASSES = [
  'PASSWORD_RESET',
  'MFA_FACTOR_REPLACEMENT',
  'RECOVERY_CODE_REGENERATION',
  'VERIFIED_EMAIL_CHANGE',
  'VERIFIED_MOBILE_CHANGE',
  'IDENTITY_UNLOCK',
  'COMPROMISED_CREDENTIAL_RECOVERY',
  'PRIVILEGED_ACCOUNT_RECOVERY',
  'SUPER_ADMIN_EMERGENCY_RECOVERY',
] as const;
export type RecoveryOperationClass = (typeof RECOVERY_OPERATION_CLASSES)[number];
