export const RECOVERY_NOTIFICATION_TYPES = [
  'RECOVERY_REQUEST_INITIATED',
  'RECOVERY_CHALLENGE_SENT',
  'PASSWORD_RESET_COMPLETED',
  'MFA_RESET_COMPLETED',
  'TRUSTED_DEVICE_REMOVED',
  'CONTACT_INFORMATION_UPDATED',
  'RECOVERY_COMPLETED',
  'SUSPICIOUS_RECOVERY_ATTEMPT',
] as const;
export type RecoveryNotificationType = (typeof RECOVERY_NOTIFICATION_TYPES)[number];

export const RECOVERY_NOTIFICATION_DELIVERY_STATES = [
  'PENDING',
  'DISPATCHED',
  'DELIVERED',
  'FAILED',
] as const;
export type RecoveryNotificationDeliveryState =
  (typeof RECOVERY_NOTIFICATION_DELIVERY_STATES)[number];
