// --- M08-M2 persistence tokens ---
export const ORDER_RETENTION_CONFIGURATION = Symbol('ORDER_RETENTION_CONFIGURATION');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');

// --- M08-M3 application service tokens ---
export const ORDER_APPLICATION_SERVICE = Symbol('ORDER_APPLICATION_SERVICE');
export const ORDER_SNAPSHOT_READ_ADAPTER = Symbol('ORDER_SNAPSHOT_READ_ADAPTER');
export const ORDER_INVENTORY_CONFIRMATION_ADAPTER = Symbol('ORDER_INVENTORY_CONFIRMATION_ADAPTER');
export const ORDER_PRODUCT_CATALOG_READ_ADAPTER = Symbol('ORDER_PRODUCT_CATALOG_READ_ADAPTER');
export const ORDER_CUSTOMER_PROFILE_READ_ADAPTER = Symbol('ORDER_CUSTOMER_PROFILE_READ_ADAPTER');

// --- M08-M4 authorization tokens ---
export const ORDER_ADMIN_AUTHORIZATION = Symbol('ORDER_ADMIN_AUTHORIZATION');
export const ORDER_SELF_SERVICE_PERMISSION_GUARD = Symbol('ORDER_SELF_SERVICE_PERMISSION_GUARD');
export const ORDER_ADMIN_PERMISSION_GUARD = Symbol('ORDER_ADMIN_PERMISSION_GUARD');
