// --- M09-M2 persistence tokens ---
export const PAYMENT_RETENTION_CONFIGURATION = Symbol('PAYMENT_RETENTION_CONFIGURATION');
export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');

// --- M09-M3 application service tokens ---
export const PAYMENT_APPLICATION_SERVICE = Symbol('PAYMENT_APPLICATION_SERVICE');
export const PAYMENT_PROVIDER = Symbol('PAYMENT_PROVIDER');
export const PAYMENT_ORDER_READ = Symbol('PAYMENT_ORDER_READ');
export const PAYMENT_ORDER_WRITE = Symbol('PAYMENT_ORDER_WRITE');

// --- M09-M4 authorization tokens ---
export const PAYMENT_ADMIN_AUTHORIZATION = Symbol('PAYMENT_ADMIN_AUTHORIZATION');
export const PAYMENT_SELF_SERVICE_PERMISSION_GUARD = Symbol(
  'PAYMENT_SELF_SERVICE_PERMISSION_GUARD',
);
export const PAYMENT_ADMIN_PERMISSION_GUARD = Symbol('PAYMENT_ADMIN_PERMISSION_GUARD');
